services:
  db:
    image: postgres
    container_name: db
    # restart: always
    env_file:
      - .env    
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - library_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  library_network:
    driver: bridge
volumes:
  db-data:
